apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-config
  namespace: openshift-gitops
data:
  metricProviderPlugins: |-
    - name: argoproj-labs/metric-ai
      location: file:///home/argo-rollouts/plugin-bin-custom/rollouts-plugin-metric-ai

