apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-rollouts
  namespace: openshift-gitops
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argo-rollouts
  template:
    spec:
      containers:
      - name: argo-rollouts
        volumeMounts:
        - name: github-secret
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: github-secret
        secret:
          secretName: argo-rollouts
          items:
          - key: github_token
            path: github_token

