apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - rolloutmanager.yaml
  - cert-cm.yaml
  # secret.yaml is managed manually (not in git due to .gitignore)
  # Create it with: oc apply -f system/progressive-delivery-controller/secret.yaml
  - namespace-role.yaml

patches:
  - path: rbac-patch.yaml
    target:
      kind: ClusterRole
      name: argo-rollouts
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: argo-rollouts-config
  - path: deployment-secret-patch.yaml
    target:
      kind: Deployment
      name: argo-rollouts
  - path: deployment-initcontainer-patch.yaml
    target:
      kind: Deployment
      name: argo-rollouts

