apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-rollouts

resources:
  - argo-rollouts-ns.yaml
  - rolloutmanager.yaml
  - cert-cm.yaml
  - secret.yaml
  - namespace-role.yaml

patches:
  - path: rbac-patch.yaml
    target:
      kind: ClusterRole
      name: argo-rollouts

